services:
  db:
    image: mysql:latest
    env_file:
      - mysql_server.env
      - mysql_credentials.env
    networks:
      - quarrel-network
    volumes:
      - "./mysql_init:/docker-entrypoint-initdb.d"
      - "./data/mysql:/var/lib/mysql"
  web:
    build: .
    develop:
      watch:
        - action: sync
          path: ./public
          target: /var/www/html
    depends_on:
      - db
    ports:
      - 80:80
    networks:
      - quarrel-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - quarrel-network
networks:
  quarrel-network:
    driver: bridge
